// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtv_7fIdbrVd1anUNQCjmHxdst0N-lVog',
    appId: '1:764067695846:web:18eb6d51576cdf5d03ff27',
    messagingSenderId: '764067695846',
    projectId: 'anmol-portfolio-30e23',
    authDomain: 'anmol-portfolio-30e23.firebaseapp.com',
    storageBucket: 'anmol-portfolio-30e23.firebasestorage.app',
    measurementId: 'G-MS8DBQPQ9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACaI5DZi7f52FyrHjPPgsB1tfuQkGMNd4',
    appId: '1:764067695846:android:630360a627c7565503ff27',
    messagingSenderId: '764067695846',
    projectId: 'anmol-portfolio-30e23',
    storageBucket: 'anmol-portfolio-30e23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADl-9zBikVsNDMW7EIlFZai1XomVTL5hA',
    appId: '1:764067695846:ios:ebb94c8de0341a7303ff27',
    messagingSenderId: '764067695846',
    projectId: 'anmol-portfolio-30e23',
    storageBucket: 'anmol-portfolio-30e23.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADl-9zBikVsNDMW7EIlFZai1XomVTL5hA',
    appId: '1:764067695846:ios:ebb94c8de0341a7303ff27',
    messagingSenderId: '764067695846',
    projectId: 'anmol-portfolio-30e23',
    storageBucket: 'anmol-portfolio-30e23.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtv_7fIdbrVd1anUNQCjmHxdst0N-lVog',
    appId: '1:764067695846:web:a8967d2148bda72903ff27',
    messagingSenderId: '764067695846',
    projectId: 'anmol-portfolio-30e23',
    authDomain: 'anmol-portfolio-30e23.firebaseapp.com',
    storageBucket: 'anmol-portfolio-30e23.firebasestorage.app',
    measurementId: 'G-6H85SXDEJN',
  );

}